server:
  port: 8202
spring:
  application:
    name: springboot-sso-server8202
  redis:
    host: 127.0.0.1
    port: 6379
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    suffix: .ftl
    template-loader-path=classpath: /templates